### ISSUE TITLE
Create Appbar for the click-short

### ISSUE THREAD

**Issue by Abhishek-kumar09** [codeforcauseorg/click-short#9]
Design: 
https://www.figma.com/file/CXLx3Y53BuswYzSvoH1n2U/click-short?node-id=0%3A1

Appbar is needed to be created in React with Material-ui.

**Comment by ritik-vashist** [comment]
@Abhishek-kumar09 I would like to work on it. Please assign this task to me.

**Comment by Abhishek-kumar09** [comment]
@ritik-vashist  Are you working on it?

**Comment by ritik-vashist** [comment]
@Abhishek-kumar09  i was waiting for your reply to get  this issue assigned.

**Comment by Rathoresourabh** [comment]
@Abhishek-kumar09 I was working on this and I have created a PR for the same , kindly have a look into it and if there any changes let me know for the same .
